### ISSUE TITLE
Anmerkungen

### ISSUE THREAD

**Issue by uridmo** [DavidBamert/Kansai#1]
Hier kurz einige Dinge die mir aufgefallen sind:

- dz sollte teil (ein Attribut) der layer class sein, falls ihr grundätzlich einen bestimmten wert vorschlagen wollt könnt ihr das mit einem keyword argument machen
- Klassennamen beginnen generell mit einem Grossbuchstaben
- Die layers sollten ein Attribut der Assembly class sein
- Wenn ihr eine Methode oder Klasse beschreiben wollt, dann als docstring
- braucht doch np.linspace anstatt np.arange (sauberer)

**Comment by DavidBamert** [comment]
habe alles behoben und Aufgeräumt.
der code funktioniert jetzt für beliebig viele layers. 
das dz kann für jede layer gewählt werden und passt sich automatisch an. 
np.linspace verwirrt mich im moment noch, deshalb ist noch arange drin. 

Die Formel in der Iteration hatte Fehler, die Kurven sehen jetzt plausibel aus. 
LG David
