### ISSUE TITLE
Reduce time needed for calculation

### ISSUE THREAD

**Issue by ghost** [DavidBamert/Kansai#9]
What slows down the code running is
fv, f1, f2 = self.get_variabledata()
putted in the loop for each "solve" function in the model class. This recall the "get_factors" function in the assembly class.
We need to refine this issue, because it takes minutes to run a code with a real case input!

**Comment by DavidBamert** [comment]
hey luca i was suspecting this to be the case. 
its easily resolvable if we pull this line of code out of the for loop. 

but i dont know how we can resolve this issue in the future, when the non-linearity acutally needs to be accounted for
